"""Initial migration.

Revision ID: 722be3a2ca7a
Revises: 
Create Date: 2022-11-21 20:16:54.098049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722be3a2ca7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
